#!/usr/bin/env python3
"""Generate ordinary Wilf classes from shape-Wilf classes plus D8 symmetry.

Framework:
  vertices = shape-Wilf classes from reverse_k*.json
  edges    = D8 plot-symmetry bridges between classes
  output   = connected components, interpreted as generated ordinary Wilf classes

The input JSONs currently use the legacy key ``record_classes``.  In this
script we interpret that key as shape-Wilf classes, following the corrected
interpretation in generating_wilf_classes.html.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, deque
from pathlib import Path
from typing import Iterable


def parse_pattern(text: str) -> tuple[int, ...]:
    text = text.strip()
    if not text:
        raise ValueError("empty pattern")
    if any(ch in text for ch in ", "):
        return tuple(int(x) for x in text.replace(",", " ").split())
    return tuple(int(ch) for ch in text)


def format_pattern(pattern: Iterable[int]) -> str:
    return "".join(str(x) for x in pattern)


def reverse_pattern(p: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(reversed(p))


def complement_pattern(p: tuple[int, ...]) -> tuple[int, ...]:
    k = len(p)
    return tuple(k + 1 - x for x in p)


def inverse_pattern(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, x in enumerate(p, start=1):
        inv[x - 1] = i
    return tuple(inv)


def d8_orbit(p: tuple[int, ...]) -> set[tuple[int, ...]]:
    """Return the square-dihedral D8 orbit generated by r, c, inverse."""
    seen = {p}
    q = deque([p])
    while q:
        x = q.popleft()
        for op in (reverse_pattern, complement_pattern, inverse_pattern):
            y = op(x)
            if y not in seen:
                seen.add(y)
                q.append(y)
    return seen


def load_shape_classes(path: Path) -> tuple[int, list[set[tuple[int, ...]]], dict]:
    data = json.loads(path.read_text())
    if "k" not in data:
        raise ValueError(f"{path} has no 'k' field")
    k = int(data["k"])
    raw_classes = data.get("record_classes")
    if raw_classes is None:
        raw_classes = data.get("shape_wilf_classes")
    if raw_classes is None:
        raise ValueError(f"{path} has neither 'record_classes' nor 'shape_wilf_classes'")

    classes: list[set[tuple[int, ...]]] = []
    seen: dict[tuple[int, ...], int] = {}
    for idx, cls in enumerate(raw_classes):
        patterns = {parse_pattern(p) for p in cls.get("patterns", [])}
        if not patterns:
            continue
        for p in patterns:
            if len(p) != k:
                raise ValueError(f"pattern {format_pattern(p)} has length {len(p)}, expected {k}")
            if sorted(p) != list(range(1, k + 1)):
                raise ValueError(f"pattern {format_pattern(p)} is not a permutation of 1..{k}")
            if p in seen:
                raise ValueError(
                    f"pattern {format_pattern(p)} occurs in both class {seen[p]} and class {idx}"
                )
            seen[p] = len(classes)
        classes.append(patterns)
    return k, classes, data


def complete_d8_images(
    classes: list[set[tuple[int, ...]]],
) -> tuple[list[set[tuple[int, ...]]], list[tuple[int, ...]]]:
    """Add missing D8 images as singleton classes.

    This is useful when the input file omits singleton classes.  For k=5,
    reverse_k5.json contains 119 patterns and omits 23451; since 23451 is a
    D8 image of included patterns, adding it gives a closed 120-pattern universe.
    """
    all_patterns = set().union(*classes) if classes else set()
    missing: set[tuple[int, ...]] = set()
    for p in list(all_patterns):
        missing.update(d8_orbit(p) - all_patterns)
    completed = [set(c) for c in classes]
    for p in sorted(missing):
        completed.append({p})
    return completed, sorted(missing)


def build_components(classes: list[set[tuple[int, ...]]]) -> list[dict]:
    pattern_to_class: dict[tuple[int, ...], int] = {}
    for i, cls in enumerate(classes):
        for p in cls:
            pattern_to_class[p] = i

    adj = [set([i]) for i in range(len(classes))]
    for i, cls in enumerate(classes):
        orbit_union: set[tuple[int, ...]] = set()
        for p in cls:
            orbit_union.update(d8_orbit(p))
        for q in orbit_union:
            j = pattern_to_class.get(q)
            if j is not None:
                adj[i].add(j)
                adj[j].add(i)

    seen: set[int] = set()
    components: list[dict] = []
    for i in range(len(classes)):
        if i in seen:
            continue
        q = deque([i])
        seen.add(i)
        nodes: list[int] = []
        while q:
            v = q.popleft()
            nodes.append(v)
            for w in adj[v]:
                if w not in seen:
                    seen.add(w)
                    q.append(w)
        patterns = set().union(*(classes[v] for v in nodes))
        components.append({"class_indices": sorted(nodes), "patterns": sorted(patterns)})

    components.sort(key=lambda c: (-len(c["patterns"]), [format_pattern(p) for p in c["patterns"]]))
    return components


def make_report(
    *,
    source: Path,
    k: int,
    original_classes: list[set[tuple[int, ...]]],
    completed_classes: list[set[tuple[int, ...]]],
    added_singletons: list[tuple[int, ...]],
    components: list[dict],
) -> dict:
    original_patterns = set().union(*original_classes) if original_classes else set()
    completed_patterns = set().union(*completed_classes) if completed_classes else set()
    generated = []
    for idx, comp in enumerate(components, start=1):
        pats = [format_pattern(p) for p in comp["patterns"]]
        generated.append(
            {
                "id": idx,
                "size": len(pats),
                "patterns": pats,
                "component_vertex_count": len(comp["class_indices"]),
                "source_class_indices": [i for i in comp["class_indices"] if i < len(original_classes)],
                "added_singleton_indices": [i for i in comp["class_indices"] if i >= len(original_classes)],
            }
        )

    return {
        "description": "Ordinary Wilf classes generated by shape-Wilf classes plus D8 plot-symmetry closure.",
        "source": str(source),
        "k": k,
        "input_shape_wilf_class_count": len(original_classes),
        "input_pattern_count": len(original_patterns),
        "completed_pattern_count": len(completed_patterns),
        "d8_added_singletons": [format_pattern(p) for p in added_singletons],
        "generated_class_count": len(generated),
        "generated_non_singleton_count": sum(1 for c in generated if c["size"] > 1),
        "generated_size_distribution": dict(sorted(Counter(c["size"] for c in generated).items())),
        "generated_wilf_classes": generated,
    }


def write_text_report(report: dict, path: Path) -> None:
    lines = []
    lines.append("Generated ordinary Wilf classes from shape-Wilf + D8 closure")
    lines.append("=" * 68)
    lines.append(f"source: {report['source']}")
    lines.append(f"k: {report['k']}")
    lines.append(f"input shape-Wilf classes: {report['input_shape_wilf_class_count']}")
    lines.append(f"input patterns: {report['input_pattern_count']}")
    lines.append(f"completed patterns: {report['completed_pattern_count']}")
    lines.append(f"D8-added singleton patterns: {', '.join(report['d8_added_singletons']) or '(none)'}")
    lines.append(f"generated classes: {report['generated_class_count']}")
    lines.append(f"generated non-singleton classes: {report['generated_non_singleton_count']}")
    lines.append(f"size distribution: {report['generated_size_distribution']}")
    lines.append("")
    for cls in report["generated_wilf_classes"]:
        lines.append(f"Class {cls['id']:02d} | size {cls['size']:2d} | vertices {cls['component_vertex_count']:2d}")
        lines.append("  " + " ".join(cls["patterns"]))
    path.write_text("\n".join(lines) + "\n")


def parse_wilf_txt(path: Path, k: int) -> list[frozenset[str]]:
    """Parse the non-singleton S_k Wilf classes from a wilf.txt file."""
    text = path.read_text()
    pattern = rf"S_{k} Wilf non-singleton classes:\s*(.*?)(?:\r?\n\s*S_{k + 1} Wilf non-singleton classes:|\Z)"
    match = re.search(pattern, text, flags=re.S)
    if not match:
        raise ValueError(f"could not find S_{k} Wilf section in {path}")

    classes: list[frozenset[str]] = []
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        m = re.match(r"size\s+(\d+):\s+(.*)$", line)
        if not m:
            raise ValueError(f"could not parse line in S_{k} section: {raw_line!r}")
        declared_size = int(m.group(1))
        patterns = m.group(2).split()
        if len(patterns) != declared_size:
            raise ValueError(
                f"declared size {declared_size}, but found {len(patterns)} patterns in line: {raw_line!r}"
            )
        classes.append(frozenset(patterns))
    return classes


def compare_with_wilf_txt(report: dict, wilf_path: Path) -> tuple[bool, list[str]]:
    k = int(report["k"])
    expected = set(parse_wilf_txt(wilf_path, k))
    generated = {frozenset(cls["patterns"]) for cls in report["generated_wilf_classes"]}
    lines = [f"checked against {wilf_path}"]
    lines.append(f"wilf.txt S_{k} classes: {len(expected)}")
    lines.append(f"generated classes: {len(generated)}")
    lines.append(
        "wilf.txt size distribution: "
        + str(dict(sorted(Counter(len(c) for c in expected).items())))
    )
    lines.append(
        "generated size distribution: "
        + str(dict(sorted(Counter(len(c) for c in generated).items())))
    )
    ok = expected == generated
    generated_patterns = {pattern for cls in generated for pattern in cls}
    pattern_to_expected = {pattern: cls for cls in expected for pattern in cls}
    intersected_expected = {
        pattern_to_expected[pattern]
        for pattern in generated_patterns
        if pattern in pattern_to_expected
    }
    exact_on_intersected_universe = generated == intersected_expected
    lines.append(f"exact class-set match: {ok}")
    lines.append(f"generated pattern count: {len(generated_patterns)}")
    touched_patterns = set().union(*intersected_expected) if intersected_expected else set()
    lines.append(f"wilf.txt patterns touched by generated classes: {len(touched_patterns)}")
    lines.append(f"wilf.txt classes touched by generated classes: {len(intersected_expected)}")
    lines.append(f"exact match on generated/intersected pattern universe: {exact_on_intersected_universe}")
    if not ok:
        missing = expected - generated
        extra = generated - expected
        if exact_on_intersected_universe and missing and not extra:
            lines.append(
                "note: generated classes are an exact subset of wilf.txt classes on the "
                "patterns present in the generated D8-closed universe; the mismatch comes "
                "from additional wilf.txt classes outside that universe."
            )
        if missing:
            lines.append("classes in wilf.txt but not generated:")
            for cls in sorted(missing, key=lambda c: (len(c), sorted(c))):
                lines.append(f"  size {len(cls)}: {' '.join(sorted(cls))}")
        if extra:
            lines.append("classes generated but not in wilf.txt:")
            for cls in sorted(extra, key=lambda c: (len(c), sorted(c))):
                lines.append(f"  size {len(cls)}: {' '.join(sorted(cls))}")
    return ok, lines


def main_args(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/reverse_k5.json"),
        help="shape-Wilf class JSON, default: data/reverse_k5.json",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=Path("outputs/generated_wilf_k5_from_shape_d8.json"),
    )
    parser.add_argument(
        "--output-txt",
        type=Path,
        default=Path("outputs/generated_wilf_k5_from_shape_d8.txt"),
    )
    parser.add_argument(
        "--no-complete-d8-images",
        action="store_true",
        help="do not add missing D8 images as singleton classes",
    )
    parser.add_argument(
        "--check-wilf",
        type=Path,
        help="optional wilf.txt file to compare against after generation",
    )
    parser.add_argument(
        "--allow-intersected-wilf-match",
        action="store_true",
        help=(
            "when --check-wilf is used, return success if generated classes match "
            "the wilf.txt classes touched by the generated pattern universe, even if "
            "wilf.txt contains additional classes outside that universe"
        ),
    )
    args = parser.parse_args(argv)

    k, shape_classes, _ = load_shape_classes(args.input)
    if args.no_complete_d8_images:
        completed_classes = [set(c) for c in shape_classes]
        added_singletons: list[tuple[int, ...]] = []
    else:
        completed_classes, added_singletons = complete_d8_images(shape_classes)

    components = build_components(completed_classes)
    report = make_report(
        source=args.input,
        k=k,
        original_classes=shape_classes,
        completed_classes=completed_classes,
        added_singletons=added_singletons,
        components=components,
    )

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_txt.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(report, indent=2) + "\n")
    write_text_report(report, args.output_txt)

    print(f"k={report['k']}")
    print(f"input shape-Wilf classes: {report['input_shape_wilf_class_count']}")
    print(f"input patterns: {report['input_pattern_count']}")
    print(f"completed patterns: {report['completed_pattern_count']}")
    added = report["d8_added_singletons"]
    if len(added) <= 20:
        added_text = ", ".join(added) or "(none)"
    else:
        added_text = f"{len(added)} patterns; see JSON/text output for full list"
    print(f"D8-added singleton patterns: {added_text}")
    print(f"generated classes: {report['generated_class_count']}")
    print(f"generated non-singleton classes: {report['generated_non_singleton_count']}")
    print(f"size distribution: {report['generated_size_distribution']}")
    print(f"wrote {args.output_json}")
    print(f"wrote {args.output_txt}")
    if args.check_wilf:
        ok, lines = compare_with_wilf_txt(report, args.check_wilf)
        print("")
        print("Wilf check")
        print("----------")
        for line in lines:
            print(line)
        if not ok:
            exact_on_intersected = any(
                line == "exact match on generated/intersected pattern universe: True"
                for line in lines
            )
            if not (args.allow_intersected_wilf_match and exact_on_intersected):
                return 1
    return 0


def main() -> int:
    return main_args()


if __name__ == "__main__":
    raise SystemExit(main())
